<a href="https://colab.research.google.com/github/alitourani/deep-learning-from-scratch/blob/main/Codes/CNNs/0_KerasConvolutionLayer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**I. Convolution Layers**
- [Conv1D Layer](https://keras.io/api/layers/convolution_layers/convolution1d)
- [Conv2D Layer](https://keras.io/api/layers/convolution_layers/convolution2d)
- [Conv3D Layer](https://keras.io/api/layers/convolution_layers/convolution3d)
- [Other Conv Layers](https://keras.io/api/layers/convolution_layers/)

**I. 1D CNNs (Temporal Convolution)**

In [58]:
import numpy as np

input = np.array([1, 1, 1, 0, 1, 0, 0, 1, 1, 0]) # Input length: 10
kernel = np.array([1, -1, 0])
output = np.zeros(8) # The convolution result will have 8 items

for index in range(8):
    output[index] = (kernel * input[index:index+3]).sum()

print('Output: ', output)

Output:  [ 0.  0.  1. -1.  1.  0. -1.  0.]


We can simply implement this code in Keras:

In [64]:
import numpy as np
from keras.models import Sequential
from tensorflow.keras.layers import Conv1D

input = np.array([1, 1, 1, 0, 1, 0, 0, 1, 1, 0])

# Let's prepare it for Keras
input = input.reshape(1, 10, 1) # One input sample, with the length of 10, with one channel

# Create a model
model = Sequential()
model.add(Conv1D(1, 3, input_shape=(10, 1))) # Our model has One filter with the shape (length) of 3

kernel = np.array([[[1]],[[-1]],[[0]]]) # Based on the structure of weights
weights = [np.array(kernel), np.array([0.0])]

# Use the weights in the model
model.set_weights(weights)

output = model.predict(input)
print('Output: ', output)

Output:  [[[ 0.]
  [ 0.]
  [ 1.]
  [-1.]
  [ 1.]
  [ 0.]
  [-1.]
  [ 0.]]]


**II. 2D CNNs**

Recall the example we have analyzed: ([CNN Slides](https://github.com/alitourani/deep-learning-from-scratch/blob/main/Slides/7-Convolutional%20Neural%20Neworks.pdf) - Page 40)

In [60]:
import numpy as np

input = [[1, 0, 1, 0, 1], 
    [1, 1, 1, 0, 0],
    [1, 0, 1, 1, 0],
    [0, 0, 1, 0, 1],
    [0, 1, 1, 1, 0]]
input = np.asarray(input)
kernel = np.array([[1, 0, 1], [0, 1, 1], [1, 0, 1]])

kernelSize = kernel.shape[0]
outputSize = input.shape[0] - kernelSize + 1

output = np.zeros([outputSize, outputSize])

print(f'A {input.shape} matrix, with an kernel of size {kernel.shape}\n')

for outerIndex in range(outputSize):
    for innerIndex in range(outputSize):
        output[outerIndex, innerIndex] = (input[outerIndex:outerIndex+3, innerIndex:innerIndex+3] * kernel).sum()

print('Output:\n', output)

A (5, 5) matrix, with an kernel of size (3, 3)

Output:
 [[6. 2. 3.]
 [4. 3. 4.]
 [4. 4. 3.]]


We can simply implement this code in Keras as well:

In [66]:
import numpy as np
from tensorflow.keras.layers import Conv2D

input = [[1, 0, 1, 0, 1], 
    [1, 1, 1, 0, 0],
    [1, 0, 1, 1, 0],
    [0, 0, 1, 0, 1],
    [0, 1, 1, 1, 0]]
input = np.asarray(input) # The input is 5x5

# Let's prepare it for Keras
input = input.reshape(1, 5, 5, 1) # One input sample, with the 5 rows and 5 columns, with one channel

# Create a model
model = Sequential()
model.add(Conv2D(1, (3,3), input_shape=(5, 5, 1))) # Our model has One filter with the shape (length) of 3x3

kernel = [[[[1]],[[0]],[[1]]],
            [[[0]],[[1]],[[1]]],
            [[[1]],[[0]],[[1]]]] # Based on the structure of weights
weights = [np.array(kernel), np.array([0.0])]

# Use the weights in the model
model.set_weights(weights)

output = model.predict(input)
print('Output: ', output)

Output:  [[[[6.]
   [2.]
   [3.]]

  [[4.]
   [3.]
   [4.]]

  [[4.]
   [4.]
   [3.]]]]


Let's apply some convolution filters on images?

In [94]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, Flatten, Dense

rows, columns = 28, 28 # Resolution of the input image

# Create a model
model = Sequential()
model.add(Conv2D(10, kernel_size=3, activation='relu', input_shape=(rows, columns, 1)))
model.add(Flatten())
model.add(Dense(3, activation='softmax'))

model.summary()

Model: "sequential_25"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_9 (Conv2D)            (None, 26, 26, 10)        100       
_________________________________________________________________
flatten_5 (Flatten)          (None, 6760)              0         
_________________________________________________________________
dense_5 (Dense)              (None, 3)                 20283     
Total params: 20,383
Trainable params: 20,383
Non-trainable params: 0
_________________________________________________________________
